services:
  - type: web
    name: postit-backend
    env: node
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000

  - type: static
    name: postit-frontend
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://postit-backend.onrender.com
